{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agentmemory.fullname" . }}-auth
  labels:
    {{- include "agentmemory.labels" . | nindent 4 }}
  {{- if .Values.auth.autoGenerate }}
  annotations:
    "helm.sh/resource-policy": keep
  {{- end }}
type: Opaque
data:
  {{- if .Values.auth.autoGenerate }}
  agentmemory-secret: {{ randAlphaNum 32 | b64enc | quote }}
  {{- else }}
  agentmemory-secret: {{ .Values.auth.secret | b64enc | quote }}
  {{- end }}
{{- end }}
