apiVersion: v1
kind: Service
metadata:
  name: {{ include "agentmemory.fullname" . }}
  labels:
    {{- include "agentmemory.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.ports.stream }}
      targetPort: stream
      protocol: TCP
      name: stream
    - port: {{ .Values.service.ports.viewer }}
      targetPort: viewer
      protocol: TCP
      name: viewer
    - port: {{ .Values.service.ports.engine }}
      targetPort: engine
      protocol: TCP
      name: engine
    - port: {{ .Values.service.ports.metrics }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "agentmemory.selectorLabels" . | nindent 4 }}
