apiVersion: v1
kind: Service
metadata:
  name: {{ include "sptFika.fullname" . }}
  labels:
    {{- include "sptFika.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: server
      port: {{ .Values.service.serverService.port }}
      targetPort: server
      protocol: {{ .Values.service.serverService.protocol}}
    - name: headless
      port: {{ .Values.service.headlessService.port }}
      targetPort: headless
      protocol: {{ .Values.service.headlessService.protocol}}
  selector:
    {{- include "sptFika.selectorLabels" . | nindent 4 }}

