# Default values for kometa cron job.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: lscr.io/linuxserver/kometa
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

schedule: "0 0 * * *"
restartPolicy: OnFailure
podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  runAsUser: 5000
  runAsGroup: 1001

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 2
    memory: 2Gi
  requests:
    cpu: 1
    memory: 128Mi


#PVC for config
persistence:
  config:
    # Optionally specify claimName to manually override the PVC to be used for
    # the config directory. If claimName is specified, storageClass and size
    # are ignored.
    # claimName: ""
    # Optionally specify a storage class to be used for the transcode directory.
    # If not specified and claimName is not specified, the default storage
    # class will be used.
    storageClass: "freenas-nfs-csi"
    subPath: "config.yaml"
    # The requested size of the volume to be used when creating a
    # PersistentVolumeClaim.
    size: 20Gi
    # Access mode for this volume
    accessMode: ReadWriteMany
  movie:
    subPath: "movies.yaml"
  tv:
    subPath: "tv-shows.yaml"
  

configmap:
  kometa:
    name: "kometa-config"
    config: | 
      libraries:
        Movies:
          collection_files:
            - file: config/movies.yaml
        TV Shows:
          collection_files:
            - file: config/tv.yaml
      settings:
        cache: true
        cache_expiration: 60
        asset_directory: config/assets
        asset_folders: true
        asset_depth: 0
        create_asset_folders: false
        dimensional_asset_rename: false
        download_url_assets: false
        show_missing_season_assets: false
        sync_mode: append
        minimum_items: 1
        default_collection_order:
        delete_below_minimum: true
        delete_not_scheduled: false
        run_again_delay: 2
        missing_only_released: false
        only_filter_missing: false
        show_unmanaged: true
        show_filtered: false
        show_options: false
        show_missing: true
        show_missing_assets: true
        save_report: true
        tvdb_language: eng
        ignore_ids:
        ignore_imdb_ids:
        playlist_sync_to_users: all
        verify_ssl: true
      plex:
        url: http://PLEX_IP_HERE:32400
        token: YOUR_TOKEN_HERE
        timeout: 60
        db_cache: 
        clean_bundles: false
        empty_trash: false
        optimize: false
      tmdb:
        apikey: YOUR_API_KEY_HERE
        language: en
      tautulli:
        url: http://TAUTULLI_IP_HERE:8182
        apikey: TAUTULLI_API_KEY_HERE
      omdb:
        apikey: OMDB_API_KEY
      radarr:
        url: http://RADARR_IP_HERE:7878
        token: RADARR_TOKEN_HERE
        add_missing: false
        root_folder_path: /movies
        monitor: false
        availability: cinemas
        quality_profile: HD - 720p/1080p
        tag: kometa
        add_existing: false
        search: false
        radarr_path:
        plex_path:
      sonarr:
        url: http://SONARR_IP_HERE:8989
        token: SONARR_TOKEN_HERE
        add_missing: false
        add_existing: false
        root_folder_path: /tv
        monitor: pilot
        quality_profile: HD - 720p/1080p
        language_profile: English
        series_type: standard
        season_folder: true
        tag: kometa
        search: true
        cutoff_search: false
        sonarr_path:
        plex_path:
      trakt:
        client_id: YOUR_CLIENT_ID_HERE
        client_secret: YOUR_CLIENT_SECRET_HERE
        authorization:
            access_token: YOUR_ACCESS_TOKEN_HERE
            token_type: Bearer
            expires_in: 7889237
            refresh_token: YOUR_REFERSH_TOKEN_HERE
            scope: public
            created_at: 1642462048

  movie:
    name: "movie-config"
    data: "" 
  tv:
    name: "tv-config"
    data: ""

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true