apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "omniroute.fullname" . }}
  labels:
    {{- include "omniroute.labels" . | nindent 4 }}
{{- if .Values.serviceAccount.automount }}
automountServiceAccountToken: true
{{- end }}