name: PR Agent

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
  issue_comment:

jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ${{ github.event.repository.private && 'self-hosted' || 'ubuntu-latest' }}
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run PR Agent on every pull request
    steps:
      - name: PR Agent action step
        id: pragent
        uses: the-pr-agent/pr-agent@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          config.model: "openrouter/deepseek/deepseek-coder"
          config.fallback_models: '["openrouter/deepseek/deepseek-coder"]'
          github_action_config.auto_review: "true"
          github_action_config.auto_describe: "true"
          github_action_config.auto_improve: "false"
