apiVersion: v2
appVersion: "1.16.0"
description: Helm chart to deploy a dedicated server for astroneer using
  Astroneer Dedicated Server using AstroTuxLauncher
home: https://github.com/GnorpLabs/GnorpCharts/charts/astroneer
keywords:
  - astroneer
  - server
  - kubernetes
  - helm
  - game
  - dedicated-server
  - game-server
maintainers:
  - name: v4de
    url: https://github.com/v4de
  - name: TheWhiteAmigo
    url: https://github.com/TheWhiteAmigo
name: astroneer
sources:
  - https://github.com/birdhimself/astroneer-docker
  - https://github.com/GnorpLabs/GnorpCharts/charts/astroneer
type: application
version: 0.1.0