# Default values for astroneer dedicated game server.

image:
  repository: docker.io/whalybird/astroneer-server
  tag: latest
  pullPolicy: IfNotPresent
  imagePullSecrets: []

# restartPolicy: unless-stopped

service:
  enabled: true
  annotations: {}
  labels: {}

  # For minikube, set this to NodePort, elsewhere use LoadBalancer
  # Use ClusterIP if your setup includes ingress controller
  type: ClusterIP

  # Use if you need to create a TCP health check for load balancers on cloud services.
  healthz:
    enabled: false
    name: healthz
    port: 80
    protocol: TCP
    targetPort: 80

  # Port for the service/container to listen on
  port: 7777
  protocol: UDP

# PVC for save data
persistence:
  enabled: true
  # Optionally specify claimName to manually override the PVC to be used for
  # the config directory. If claimName is specified, storageClass and size
  # are ignored.
  # claimName: ""
  mountPath: /astrotux/AstroneerServer/Astro/Saved
  size: 5Gi
  storageClass: "" # leave empty to use cluster default

  # Additional storage definitions
  #
  # Supports all storage types as defined by https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/volume/#Volume
  #
  # The objects supports configuring the mount path and the subpath.
  # If external isn't true, the defined deletion prevention, storage class, and size will be used to create a new PVC
  extra: []

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 1
  #   memory: 1Gi
  # requests:
  #   cpu: 1
  #   memory: 1Gi

# configmap to overwrite the AstroServerSettings.ini file
astroserversettings:
  path: /astrotux/AstroneerServer/Astro/Saved/Config/WindowsServer/AstroServerSettings.ini
  config: |
    [/Script/Astro.AstroServerSettings]
    bLoadAutoSave=true
    MaxServerFramerate=30
    MaxServerIdleFramerate=3.000000
    bWaitForPlayersBeforeShutdown=false
    ConsolePassword=
    PublicIP=
    ServerName=
    ServerGuid=
    OwnerName=
    OwnerGuid=
    PlayerActivityTimeout=0
    ServerPassword=
    bDisableServerTravel=false
    DenyUnlistedPlayers=false
    VerbosePlayerProperties=false
    AutoSaveGameInterval=900
    BackupSaveGamesInterval=7200
    ActiveSaveFileDescriptiveName=SAVE_1
    ShareCode=
    ServerAdvertisedName=

# env variables for AstroTuxLauncher
launcher:
  env:
    DEBUG: false # Enables debug logging. default: false
    DISABLE_ENCRYPTION: false # Disables connection encryption. default: false
    FORCE_CHOWN: false # chowns the astrotux folder on startup; potential workaround for an issue. default: false

rcon: {}
  # enable: true

  # If not provided a random password will be generated and stored as a secret
  secret: {}
  # The name of the kubernetes secret object
  # name: ""
  # The key inside the secret that contains the password value
  # key: ""

# If not provided a random password will be generated and stored as a secret
secret: {}
  # The name of the kubernetes secret object
  # name: ""
  # The key inside the secret that contains the password value
  # key: ""

# Traefik ingress config
traefik:
  enabled: true
  entryPoint: astroneer
  port: 7777

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true